### ISSUE TITLE
[Bug]: Toast is not working in version 2.1.1

### ISSUE THREAD

**Issue by ginosanterre** [materializecss/materialize#499]
### Before submitting...

- [X] I have searched for [duplicate or closed issues](https://github.com/materializecss/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue).
- [X] I have read the [CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md) and my issue is following the guidelines.
- [X] I have read the template completely before filling it in.

### Context

Since the version 2.1.1 (https://cdn.jsdelivr.net/npm/@materializecss/materialize@2.1.1/dist/js/materialize.min.js), toast don't display the message.

### Current Behavior

Since the version 2.1.1 (https://cdn.jsdelivr.net/npm/@materializecss/materialize@2.1.1/dist/js/materialize.min.js), toast don't display the message.

### Expected behavior

The message is displayed and the message in the console (M.toast is not a function) disappear.

### Possible Solutions or Causes

I don't know.

### Steps to reproduce

Open the browser console. Try one of your toast error message

### Your Environment

* Version used:2.1.1
* Browser Name and version: Brave 1.69.160
* Operating System and version (desktop or mobile): Mac
* Additional information you want to tell us:

**Comment by OlivierMadant** [comment]
Hello,

For info, I tested the new version 2.1.1 with another website and I have exactly the same problem.
I don't know why.
@wuda-io , do you think it's possible that this is related to [#496](https://github.com/materializecss/materialize/pull/496) ?

Olivier

**Comment by ginosanterre** [comment]
I get back to 2.1.0 (https://cdn.jsdelivr.net/npm/@materializecss/materialize@2.1.0/dist/js/materialize.min.js). Toast is working but the bug for M.FormSelect.init(select) is back (normal, it was fix in 2.1.1).

**Comment by Jerit3787** [comment]
> Hello,
> 
> For info, I tested the new version 2.1.1 with another website and I have exactly the same problem. I don't know why. @wuda-io , do you think it's possible that this is related to [#496](https://github.com/materializecss/materialize/pull/496) ?
> 
> Olivier

I also think that pull request causing issues (particularly on this commit 76465afea4f5ddade4eb972601b165c7cc5901aa). Some of the imports/exports for toasts are removed without any replacement when moving global.ts to index.ts.

**Comment by wuda-io** [comment]
Ok thats not good :/ maybe it is related, I was changing some things due to the tests not working properly. Also, the Toast Component is a bit special compared to the other ones, because it has no init Function or so. I will look into it and give feedback here.

The good thing is, that many things are working much faster now, so we also can make quicker releases and move forward with higher velocity.

**Comment by ginosanterre** [comment]
@wuda-io is it something that will be resolve soon?

**Comment by ginosanterre** [comment]
It seems it will be longer than expected do get the component working again.

**Comment by jonfairbanks** [comment]
@wuda-io Any line of sight on a fix for this?

**Comment by ginosanterre** [comment]
@jonfairbanks / @wuda-io any update. Normally, does it takes months to fix this kind of bugs? Does it means, if somebody break a feature with a PR, our apps cannot work for months?

**Comment by wuda-io** [comment]
It works with 2.1.1 with the constructor. I will provide a snippet later.

**Comment by wuda-io** [comment]
In version you can use 
```javascript
new M.Toast({text: 'This is a toast!'});
```

**Comment by Razzmatazzz** [comment]
Works like a charm, thanks so much!

**Comment by ginosanterre** [comment]
Does it means it's the new way to use Toast with a new and a uppercase T? Will the docs will be updated (https://materializeweb.com/toasts.html)? 

Does it mean i must close this issue?

**Comment by cmorgancli** [comment]
I hope we will have a fix that will make toasts in 2.1.1 work as they did in 2.1.0.  Code-breaking releases are a big problem.

**Comment by ginosanterre** [comment]
I hope I had not change everything to change everything again...

**Comment by gselderslaghs** [comment]
> In version 2.1.1 you can use
> 
> ```js
> new M.Toast({text: 'This is a toast!'});
> ```

Works like a charm, as expected



> I hope I had not change everything to change everything again...

@ginosanterre what do you mean by changing everything?
You should find and replace `m.toast` to `new m.Toast` in your working project codebase
This should be sufficient to make toasts work again

- [v2.1.0 CodePen example](https://codepen.io/Geert-Selderslaghs/pen/qBeLwEE)
- [v2.1.1 CodePen example](https://codepen.io/Geert-Selderslaghs/pen/RwXEOPK)

Hope those examples clarifies your concerns and fixes your issue

**Comment by ginosanterre** [comment]
It's what i did. I meant changing the code and testing everything.

**Comment by ginosanterre** [comment]
I think this issue is solved.
